In [ ]:
import numpy as np
#creating an array
arr = np.array([1,2,3,4,5])
arr


array([1, 2, 3, 4, 5])

In [ ]:
#creating a 0-D array
import numpy as np
arrzero = np.array(80)
print(arrzero)

80


In [ ]:
#creating a 2-D array
arr2 = np.array([[1,2,3,4,5],[7,8,9,10,11],[12,13,14,15,16]])
print(arr2)
print(arr2.ndim)


[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [12 13 14 15 16]]
2


In [ ]:
#number of elements
arr2.size

15

In [ ]:
#total memory taken by an array
arr2.nbytes


120

In [ ]:
arr.nbytes

8

In [ ]:
#single element size
#[[ 1 2 3 4 5]
#[ 7 8 9 10 11]]
arr2.itemsize


8

In [ ]:
#for the data type of the array
arr2.dtype

dtype('int64')

In [ ]:
print(arr2)
#[[ 1 2 3 4 5](Oth row)
#[ 7 8 9 10 11]](1st row row)


[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]


In [ ]:
#for the specific element of the array()
arr2[0,2]


3

In [ ]:
#specific row of the array
arr2[1,:]


array([ 7,  8,  9, 10, 11])

In [ ]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr3)


[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#(Start Index:Ending Index)[inclusive:exclusive]
arr3[1:5]

array([2, 3, 4, 5])

In [ ]:
print(arr3[5:])


[ 6  7  8  9 10]


In [ ]:
print(arr3[:5])


[1 2 3 4 5]


In [ ]:
print(arr2)


[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]


In [ ]:
print(arr2[1,1:4])


[ 8  9 10]


In [ ]:
#copying of an array
arr4 = arr2.copy()
print(arr4)


[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]


In [ ]:
#Zero matrix
np.ones((4,6))


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
#All 1 matrix
np.ones((6,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
#other matrix
np.full((40,40),678)


array([[678, 678, 678, ..., 678, 678, 678],
       [678, 678, 678, ..., 678, 678, 678],
       [678, 678, 678, ..., 678, 678, 678],
       ...,
       [678, 678, 678, ..., 678, 678, 678],
       [678, 678, 678, ..., 678, 678, 678],
       [678, 678, 678, ..., 678, 678, 678]])

In [ ]:
#importing random
from numpy import random

In [ ]:
x = random.randint(100)
print(x)

17


In [ ]:
import numpy as np
np.random.rand(3,3)


array([[0.72470328, 0.53443227, 0.56452147],
       [0.68873904, 0.24289207, 0.44152149],
       [0.40391415, 0.8562481 , 0.56495531]])

In [ ]:
#identity matrix
np.identity(6)


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
#Mathematical operation on array
arrm = np.array([10,20,30,40])
print(arrm)

[10 20 30 40]


In [ ]:
#plus opertaion
arrm = arrm+15
arrm


array([25, 35, 45, 55])

In [ ]:
#subtraction operation
arrm = arrm - 40
print(arrm)


[-15  -5   5  15]


In [ ]:
arrz = arrm+100
arrz


array([ 85,  95, 105, 115])

In [ ]:
#multiplication operation
print(arrm)
arrm*10


[-15  -5   5  15]


array([-150,  -50,   50,  150])

In [ ]:
#Divison operation
arrm/7

array([-2.14285714, -0.71428571,  0.71428571,  2.14285714])

In [ ]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([10,15,20,25,30])
print(a1+a2)


[11 17 23 29 35]


In [ ]:
#cos function in an array
np.cos(a1)


array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [ ]:
print(arr2)

[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [12 13 14 15 16]]


In [ ]:
#minimum value from the array
np.min(arr2)


1

In [ ]:
#maximum value from the array
np.max(arr2)


16

In [ ]:
np.sum(arr2)


130

In [ ]:
#iterating in 1-D
for x in a1:
  print(x)


NameError: name 'a1' is not defined

In [ ]:
#iterating in 2-D
for z in arr2:
 print(z)


[1 2 3 4 5]
[ 7  8  9 10 11]
[12 13 14 15 16]


In [ ]:
for a in arr2:
   for b in a:
      print(b)


1
2
3
4
5
7
8
9
10
11
12
13
14
15
16
